#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;
use Munin::Plugin;
use LWP::UserAgent;
use vars qw ($config $yamlconfig $json $debug %infohash1 %infohash2 %infohash3 $key $val);

$debug = 1;

if (@ARGV && $ARGV[0] eq "config") {
    $config = 1;
}

my $statsurl = 'http://localhost:9200/_cat/health?ts=false';

my $ua = LWP::UserAgent->new;
my $response = $ua->get (${statsurl}) or print ("WARNING: Could not read stats from $statsurl");
if ($response->is_success) {
    # cluster    status node.total node.data shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
    # hjemme-elk green           2         2    272 136    0    0        0             0                  -                100.0%
    # print $response->content, "\n";
    # my ($cluster, $status, $node_total, $node_data, $shards, $primary, $relo, $init, $unassigned, $pending_tasks, $max_task_wait_time, $active_shards_percent) = split (/\s+/, $response->content);
    my @stats = split (/\s+/, $response->content);
    foreach my $field (@stats) {
        print "Field: $field\n";
    }
    if ($config) {
      print "graph_title Elastic health\n";
    }
} else {
    print "WARNING: ", $response->status_line, "\n";
}


