#!/usr/bin/perl

use strict;
use warnings;
use JSON::XS;
use YAML::Tiny;
use Data::Dumper;
use Munin::Plugin;
use LWP::UserAgent;
use JSON qw (decode_json);
# use Scalar::Util qw/reftype/;
use vars qw ($config $yamlconfig $json $debug %infohash1 %infohash2 %infohash3 $key $val);

$debug = 1;

if (@ARGV && $ARGV[0] eq "config") {
    $config = 1;
}

# Open the config
my $yaml = YAML::Tiny->read ( '/usr/local/etc/elknodestats.yml');
# Get a reference to the first document
my $yamlconfig = $yaml->[0];

my $statsurl = 'http://localhost:9200/_nodes/stats';

my $ua = LWP::UserAgent->new;
my $response = $ua->get (${statsurl}) or print ("WARNING: Could not read stats from $statsurl");
if ($response->is_success) {
    $json = JSON::XS->new->decode ($response->content);
} else {
    print "WARNING: ", $response->status_line, "\n";
}

# print Dumper ($json), "\n\n" if $debug;
# my $clustername = $json->
    # nodes
    # cluster_name
    # _nodes
  
my $cluster_name = $json->{'cluster_name'};
my $cluster_name_config = clean_fieldname ($cluster_name);

foreach my $node (keys %{$json->{'nodes'}}) {
    # Fetch stats from each node
    # print "DEBUG ", $node, "\n" if $debug;
    my $nodename = $json->{'nodes'}->{$node}->{'name'};
    
    foreach $key (keys %{$json->{'nodes'}->{$node}}) {
	if ($yamlconfig->{$key}) { # We have YAML config for this section

	    if (ref $json->{'nodes'}->{$node}->{$key} eq ref {}) { # Is it a hash?
		# print "$json->{'nodes'}->{$node}->{$key} is a hash\n";
		foreach my $key2 (keys %{$json->{'nodes'}->{$node}->{$key}}) {
		    # print "nodes -> $node -> $key -> $key2\n";
		    if ($yamlconfig->{$key}->{$key2}) { # We have YAML config for this section, so we include it

			if (ref $json->{'nodes'}->{$node}->{$key}->{$key2} eq ref {}) {
			    # print " - $json->{'nodes'}->{$node}->{$key}->{$key2} is a hash\n";
			    foreach my $key3 (keys %{$json->{'nodes'}->{$node}->{$key}->{$key2}}) {
				# print "nodes -> $node -> $key -> $key2 -> $key3\n";
				if ($yamlconfig->{$key}->{$key2}->{$key3}) {

				    if (ref $json->{'nodes'}->{$node}->{$key}->{$key2}->{$key3} eq ref {}) { # Is it a hash?
					# print " - - $json->{'nodes'}->{$node}->{$key}->{$key2}->{$key3} is a hash\n";
				    } else {
					if ($yamlconfig->{$key}->{$key2}->{$key3}->{'munin_title'}) {
					    $infohash3{$key}->{$key2}->{$key3}->{'nodes'}->{$node}->{'label'} = $nodename;
					    $infohash3{$key}->{$key2}->{$key3}->{'nodes'}->{$node}->{'value'} = $json->{'nodes'}->{$node}->{$key}->{$key2}->{$key3};
					    $infohash3{$key}->{$key2}->{$key3}->{'title'} = $yamlconfig->{$key}->{$key2}->{$key3}->{'munin_title'};
					    $infohash3{$key}->{$key2}->{$key3}->{'type'} = $yamlconfig->{$key}->{$key2}->{$key3}->{'munin_type'} if $yamlconfig->{$key}->{$key2}->{$key3}->{'munin_type'};
                                            $infohash3{$key}->{$key2}->{$key3}->{'vlabel'} = $yamlconfig->{$key}->{$key2}->{$key3}->{'munin_vlabel'} if $yamlconfig->{$key}->{$key2}->{$key3}->{'munin_vlabel'};
                                            $infohash3{$key}->{$key2}->{$key3}->{'divide_by'} = $yamlconfig->{$key}->{$key2}->{$key3}->{'munin_divide_by'} if $yamlconfig->{$key}->{$key2}->{$key3}->{'munin_divide_by'};

					}
				    }
				}
			    }
			} else { # $key2 is not a hash, checking for name
			    if ($yamlconfig->{$key}->{$key2}->{'munin_title'}) {
				$infohash2{$key}->{$key2}->{'title'} = $yamlconfig->{$key}->{$key2}->{'munin_title'};
				$infohash2{$key}->{$key2}->{'type'} = $yamlconfig->{$key}->{$key2}->{'munin_type'} if $yamlconfig->{$key}->{$key2}->{'munin_type'};
                                $infohash2{$key}->{$key2}->{'vlabel'} = $yamlconfig->{$key}->{$key2}->{'munin_vlabel'} if $yamlconfig->{$key}->{$key2}->{'munin_vlabel'};
                                $infohash2{$key}->{$key2}->{'divide_by'} = $yamlconfig->{$key}->{$key2}->{'munin_divide_by'} if $yamlconfig->{$key}->{$key2}->{'munin_divide_by'};
				$infohash2{$key}->{$key2}->{'nodes'}->{$node}->{'label'} = $nodename;
				$infohash2{$key}->{$key2}->{'nodes'}->{$node}->{'value'} = $json->{'nodes'}->{$node}->{$key}->{$key2};
			    }
			}
		    }
		}
	    } else { # key is not a hash
		if ($yamlconfig->{$key}->{'munin_title'}) {
		    $infohash1{$key}->{'title'} = $yamlconfig->{$key}->{'munin_title'};
		    $infohash1{$key}->{'type'} = $yamlconfig->{$key}->{'munin_type'} if $yamlconfig->{$key}->{'munin_type'};
                    $infohash1{$key}->{'vlabel'} = $yamlconfig->{$key}->{'munin_vlabel'} if $yamlconfig->{$key}->{'munin_vlabel'};
                    $infohash1{$key}->{'divide_by'} = $yamlconfig->{$key}->{'munin_divide_by'} if $yamlconfig->{$key}->{'munin_divide_by'};
		    $infohash1{$key}->{'nodes'}->{$node}->{'label'} = $nodename;
		    $infohash1{$key}->{'nodes'}->{$node}->{'value'} = $json->{'nodes'}->{$node}->{$key};
		}
	    }
	}
    }
}

foreach my $key1 (keys %infohash2) {
    foreach my $key2 (keys %{$infohash2{$key1}}) {
	print "\nmultigraph elknodestats__${key1}__${key2}\n";
	my $tmptype = "";
	if ($config) {
	    my $tmptitle = $infohash2{$key1}->{$key2}->{'title'} if $infohash2{$key1}->{$key2}->{'title'};
	    $tmptype = $infohash2{$key1}->{$key2}->{'type'} if $infohash2{$key1}->{$key2}->{'type'};
	    print "graph_title ", $cluster_name, " nodes: ", $key1, " - ", $tmptitle, "\n";
	    print "graph_category Elasticstack\n";
            print "graph_vlabel ", $infohash2{$key1}->{$key2}->{'vlabel'}, "\n" if $infohash2{$key1}->{$key2}->{'vlabel'};
	}
	if ($infohash2{$key1}->{$key2}->{'nodes'}) {
	    for my $node (sort keys %{$infohash2{$key1}->{$key2}->{'nodes'}}) {
		if ($config) {
		    print $node, ".label ", $infohash2{$key1}->{$key2}->{'nodes'}->{$node}->{'label'}, "\n";
                    print $node, ".cdef ", $node, ",", $infohash2{$key1}->{$key2}->{'nodes'}->{$node}->{'divide_by'}, "/\n" if $infohash2{$key1}->{$key2}->{'nodes'}->{$node}->{'divide_by'};
		    print $node, ".type ", $tmptype, "\n" if $tmptype;
		} else {
		    print $node, ".value ", $infohash2{$key1}->{$key2}->{'nodes'}->{$node}->{'value'}, "\n";
		}
	    }
	}
    }
}

foreach my $key1 (keys %infohash3) {
    foreach my $key2 (keys %{$infohash3{$key1}}) {
	foreach my $key3 (keys %{$infohash3{$key1}->{$key2}}) {
	    print "\nmultigraph elknodestats__${key1}__${key2}__${key3}\n";
	    my $tmptype = "";
	    if ($config) {
		my $tmptitle = $infohash3{$key1}->{$key2}->{$key3}->{'title'} if $infohash3{$key1}->{$key2}->{$key3}->{'title'};
		$tmptype = $infohash3{$key1}->{$key2}->{$key3}{'type'} if $infohash3{$key1}->{$key2}->{$key3}->{'type'};
		print "graph_title ", $cluster_name, " nodes: ", $key1, " - ", $key2, " - ", $tmptitle, "\n";
		print "graph_category Elasticstack\n";
                print "graph_vlabel ", $infohash3{$key1}->{$key2}->{$key3}->{'vlabel'}, "\n" if $infohash3{$key1}->{$key2}->{$key3}->{'vlabel'};
	    }
	    if ($infohash3{$key1}->{$key2}->{$key3}->{'nodes'}) {
		for my $node (sort keys %{$infohash3{$key1}->{$key2}->{$key3}->{'nodes'}}) {
		    if ($config) {
			print $node, ".label ", $infohash3{$key1}->{$key2}->{$key3}->{'nodes'}->{$node}->{'label'}, "\n";
                        print $node, ".cdef ", $node, ",", $infohash2{$key1}->{$key2}->{$key3}->{'nodes'}->{$node}->{'divide_by'}, "/\n" if $infohash2{$key1}->{$key2}->{$key3}->{'nodes'}->{$node}->{'divide_by'};
			print $node, ".type ", $tmptype, "\n" if $tmptype;
		    } else {
			print $node, ".value ", $infohash3{$key1}->{$key2}->{$key3}->{'nodes'}->{$node}->{'value'}, "\n";
		    }
		}
	    }
	}
    }
}

